### ISSUE TITLE
Login reports missing token

### ISSUE THREAD

**Issue by jeffmikels** [bernd-wechner/Degoo#1]
Currently, when trying to log in, the following error is returned with a 403

`{"message":"Missing Authentication Token"}`

(I added debug messages to line 169 of `degoo/__init__.py`)

```python
    if CREDS != {}:
        response = requests.post(URL_login, data=json.dumps(CREDS))
        print(response.headers)
        print(response.text)
```

**Comment by bernd-wechner** [comment]
Wowsers, the API is of course a moving target as Degoo are a young and evolving business. They did tell me recently they are working on a public API. In the mean time we have to keep up ;-). I tried mine and it's working BUT I don't have to log in as logins don't expire and once logged in they deliver a couple of keys that this scrip stores in `~/.config/degoo/keys.json ` so I'm good. I'm snowed under now and won't fiund time to look at the API again for a while (maybe not this year).

But if you're keen the way to do it, is in the dev tools of  a web browser (Firefox or Chrome or Chromium are all fine) watch the networks tab as you log in, save all the requests and responses and learn from that. That's how I put it all together, just by watching that tab saving the requests, and coding them up in Python ...

**Comment by bernd-wechner** [comment]
OK, for a change of scene I made time to study this more closely. And boy was I wrong, this boils down to a mere URL change, which I've fixed. Logs in fine for me again.

To be clear and for the record, the result of login a Token that is stored for later use, and the an API key which is hardcoded (not returned by the login URL. 

Now it's not THE most user friendly system yet ;-), but here's what I tested:

1. I removed my credentials file for a clean start
2. I ran degoo_login as follows:

$ ./degoo_login
No login credentials available. Please add account details to /home/bernd/.config/degoo/credentials.json
Login failed.

3. So I edited that file and in it was one line:

`{"Username": "<your Degoo username here>", "Password": "<your Degoo password here>"}`

which I changed to:

`{"Username": "myemailaddress", "Password": "mypassword"}`

(clearly not literally myemailaddress and mypassword, by my email address and my password as I use to login to Degoo)

4. Then I ran degoo_login again:

```
$ time ./degoo_login
Successfuly logged in.

real	0m1.157s
user	0m0.234s
sys	0m0.024s
```
and I'm logged in and all the other utilities work.

This can close as fixed. But I'd cherish hearing back that it works for you.
