### ISSUE TITLE
How to Use degoo_put command ?

### ISSUE THREAD

**Issue by pingme998** [bernd-wechner/Degoo#28]
I have tried every possible command other than this.
Please anyone give a hint. or just an example.

degoo_put

```
root@093ff746f382:/Degoo# python3 degoo_put /Degoo/testuploadfile /
Traceback (most recent call last):
  File "degoo_put", line 286, in <module>
    sys.exit(main())
  File "degoo_put", line 211, in main
    result = degoo.put(args.local, args.remote, args.verbose, not args.force, args.dryrun, args.scheduled)
  File "/Degoo/degoo/util.py", line 1129, in put
    return put_file(local_path, remote_folder, verbose, if_changed, dry_run, schedule)
  File "/Degoo/degoo/util.py", line 886, in put_file
    dest = get_item(remote_folder)
  File "/Degoo/degoo/util.py", line 535, in get_item
    contents = get_children(part_id)
  File "/Degoo/degoo/util.py", line 604, in get_children
    __CACHE_CONTENTS__[dir_id] = api.getFileChildren3(dir_id)
  File "/Degoo/degoo/API.py", line 541, in getFileChildren3
    raise self.Error(f"getFileChildren3 failed with: {message}")
degoo.API.API.Error: getFileChildren3 failed with: Too large input!
degoo_put: getFileChildren3 failed with: Too large input!
           for help use --help
```

degoo_user
```
root@093ff746f382:/Degoo# python3 degoo_user    
Logged in user:
        Name: 
        Email: babunanbxgs@gmail.com
        Phone: None
        AvatarURL: 
        AccountType: Pro 500 GB
        UsedQuota: 0 Bytes
        TotalQuota: 107.4 GB
```

**Comment by bernd-wechner** [comment]
Not sure what you mean by "I have tried every possible command other than this." 

The Error reported could a bug (in reporting that is). See the trailing / in your command line. That is the root directory of you Degoo drive. Sadly the first tier (top level directories) in that root directory are called (by Degoo) "devices" and they provide no means of creating a device at all yet. 

To wit, change this to the name of one of your devices. That is try:

`degoo_ls /`

to see what devices you have, and then put into one of those and see what happens. 

I'm only guessing of course.

**Comment by bernd-wechner** [comment]
OK, looked into this and it turns out Degoo have lowered the limit on GetFileChildren requests from a huge int to a mere 1000. So I've pushed a fix for that and it's working again.
