### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by forrie** [bernd-wechner/Degoo#3]
Thank you for contributing this.  I got sucked in to Degoo, only to realize the frustration that they offer.  This is something we all need.

Consider listing some dependencies that this requires?  

From python3.8 (MacPorts, MacOS Big Sur):

Traceback (most recent call last):
  File "build.py", line 20, in <module>
    import os, stat, degoo
  File "/usr/local/src/degoo/degoo/__init__.py", line 23, in <module>
    import os, sys, csv, json, time, datetime, requests, wget, magic, humanize, humanfriendly, hashlib, base64
**ModuleNotFoundError: No module named 'requests'**

**Comment by GrowtopiaJaw** [comment]
`python3 -m pip install requests` ?

**Comment by GrowtopiaJaw** [comment]
So far, these are the only dependencies that I have to install on my Ubuntu 20.10 machine.
`python3 -m pip install appdirs wget magic python-magic humanize humanfriendly`

If anything comes up as **ModuleNotFoundError: No module named 'X'**, then just type in the command `python3 -m pip install X` or `pip3 install X` (whichever command works for you) with the X substituting the 'missing' module.

**Comment by bernd-wechner** [comment]
A requirements.txt file was kindly provided by @GrowtopiaJaw and has been merged in.
