### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by kp-emagine** [bernd-wechner/Degoo#40]
Ubuntu Server 20.04 LTS
Running `pip install -r requirements.txt`
Receive error: `ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.`

Fix: `pip install testresources` before installing the requirements, but maybe it needs to be added to them?

**Comment by bernd-wechner** [comment]
Thanks for reporting that. On the list to test when time permits. Given the rate of my repsonses here, you'll observe time hasn't permitted much of late.

**Comment by bernd-wechner** [comment]
I did just try this on a fresh box and fresh venv and didn't find this dependency was missing or needed. I don't even know why it would be as one thing sorely lacking from this hack of a project is a test bed ;-). So I'll have to assume there was some nuance with your setup. Here's what I did:
```
sudo apt install python3-venv
python -m venv ~/.venv/degoo
source ~/.venv/degoo/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
python build.py
```
and all went fine.
