### ISSUE TITLE
How do I download all Degoo files at once?

### ISSUE THREAD

**Issue by UltraJew** [bernd-wechner/Degoo#46]
Could you give an description on how to do this after installing the req's? Thanks a lot

**Comment by bernd-wechner** [comment]
Sorry I'm so slow at getting around to this and other issues. Been a lot priority in a busy life.

Nor can I quickly check on this as one reason I have time is I'm on the road, away from my workstation on a laptop after kids in bed with a moment to catch up on some belated comms.

What I can suggest is:

1. reading the source (it's all internally documented): https://github.com/bernd-wechner/Degoo/blob/master/commands.py
2. try running `degoo --help` or such. 
3. If memory serves me I'd start with `degoo ls` to see the top level root folders that Degoo call devices and then just `degoo get foldername` and see what happens ... pretty sure it downloads the whole device. 

Remember though this is a basic proof of concent reverse engineering in development with login issues known and many todos .. it's not a consumer product. You really need to take some initiative and explore it and try it out and play with it. It's in Python for the simple reason that that is arguably the most popular easily read and implemented and understood language out there ....

Good luck with it.
