### ISSUE TITLE
Any further development?

### ISSUE THREAD

**Issue by tomaasz** [bernd-wechner/Degoo#49]

**Comment by bernd-wechner** [comment]
Alas no. Waiting on a solution for the JA3 issue.

**Comment by tomaasz** [comment]
I dont know this issue
Where I can find info about this ?

**Comment by bernd-wechner** [comment]
The JA3 issue is now fixed:

https://github.com/bernd-wechner/Degoo/commit/bc92782790771faacd506e4d110622633bc120b6

Thanks to curl_cffi, a new Python package that brings KJA3 impersonation to Python. Alas, the whole package is still under testing and not what I'd call production ready by any means. But login is working again ;-).

**Comment by tomaasz** [comment]
thanks
